import type { GeoJSONFacilities } from '@/types/facilities';
import { FacilityId } from '@/consts/facilityId';
import { values } from '@/utils/object';
import { FLOOR_IMAGE_B1 } from './assets/b1';
import * as GEOJSON_FACILITIES from './geojson'

export const FACILITIES_MAP: Record<FacilityId, GeoJSONFacilities> = {
  [FacilityId.B1]: {
    id: FacilityId.B1,
    type: 'academic',
    name: '1号館',
    data: GEOJSON_FACILITIES.B1,
    floorImages: FLOOR_IMAGE_B1,
  },
  [FacilityId.B2]: {
    id: FacilityId.B2,
    type: 'academic',
    name: '2号館',
    data: GEOJSON_FACILITIES.B2,
  },
  [FacilityId.B3]: {
    id: FacilityId.B3,
    type: 'academic',
    name: '3号館',
    data: GEOJSON_FACILITIES.B3,
  },
  [FacilityId.B3_ANNEX]: {
    id: FacilityId.B3_ANNEX,
    type: 'academic',
    name: '3号館別館',
    data: GEOJSON_FACILITIES.B3_ANNEX,
  },
  [FacilityId.B4]: {
    id: FacilityId.B4,
    type: 'academic',
    name: '4号館',
    data: GEOJSON_FACILITIES.B4,
  },
  [FacilityId.B4_ANNEX]: {
    id: FacilityId.B4_ANNEX,
    type: 'academic',
    name: '4号館別館',
    data: GEOJSON_FACILITIES.B4_ANNEX,
  },
  [FacilityId.B5]: {
    id: FacilityId.B5,
    type: 'academic',
    name: '5号館講義実験棟',
    data: GEOJSON_FACILITIES.B5,
  },
  [FacilityId.B6]: {
    id: FacilityId.B6,
    type: 'academic',
    name: '6号館',
    data: GEOJSON_FACILITIES.B6,
  },
  [FacilityId.B7]: {
    id: FacilityId.B7,
    type: 'academic',
    name: '7号館',
    data: GEOJSON_FACILITIES.B7,
  },
  [FacilityId.B8]: {
    id: FacilityId.B8,
    type: 'academic',
    name: '8号館',
    data: GEOJSON_FACILITIES.B8,
  },
  [FacilityId.B9]: {
    id: FacilityId.B9,
    type: 'academic',
    name: '9号館',
    data: GEOJSON_FACILITIES.B9,
  },
  [FacilityId.B10]: {
    id: FacilityId.B10,
    type: 'academic',
    name: '10号館',
    data: GEOJSON_FACILITIES.B10,
  },
  [FacilityId.B10_OLD1]: {
    id: FacilityId.B10_OLD1,
    type: 'academic',
    name: '10号館・旧1号館',
    data: GEOJSON_FACILITIES.B10_OLD1,
  },
  [FacilityId.B11]: {
    id: FacilityId.B11,
    type: 'academic',
    name: '11号館',
    data: GEOJSON_FACILITIES.B11,
  },
  [FacilityId.B12]: {
    id: FacilityId.B12,
    type: 'academic',
    name: '12号館',
    data: GEOJSON_FACILITIES.B12,
  },
  [FacilityId.B13]: {
    id: FacilityId.B13,
    type: 'academic',
    name: '13号館',
    data: GEOJSON_FACILITIES.B13,
  },
  [FacilityId.B14]: {
    id: FacilityId.B14,
    type: 'academic',
    name: '14号館',
    data: GEOJSON_FACILITIES.B14,
  },
  [FacilityId.BIO]: {
    id: FacilityId.BIO,
    type: 'academic',
    name: 'バイオ環境化学実験棟',
    data: GEOJSON_FACILITIES.BIO,
  },
  [FacilityId.AIT_PLAZA]: {
    id: FacilityId.AIT_PLAZA,
    type: 'cafeteria',
    name: 'AITプラザ',
    data: GEOJSON_FACILITIES.PLAZA,
  },
  [FacilityId.AIWA_KAIKAN]: {
    id: FacilityId.AIWA_KAIKAN,
    type: 'cafeteria',
    name: '愛和会館',
    candidate: ['愛和食堂'],
    data: GEOJSON_FACILITIES.AIWA,
  },
  [FacilityId.CENTRAL_TERRACE]: {
    id: FacilityId.CENTRAL_TERRACE,
    type: 'cafeteria',
    name: 'セントラルテラス',
    candidate: ['セントレア'],
    data: GEOJSON_FACILITIES.CENTRAL_TERRACE,
  },
  [FacilityId.CLUBHOUSE3]: {
    id: FacilityId.CLUBHOUSE3,
    type: 'clubhouse',
    name: '第3クラブハウス',
    data: GEOJSON_FACILITIES.CLUBHOUSE3,
  },
  [FacilityId.CLUBHOUSE4]: {
    id: FacilityId.CLUBHOUSE4,
    type: 'clubhouse',
    name: '第4クラブハウス',
    data: GEOJSON_FACILITIES.CLUBHOUSE4,
  },
  [FacilityId.CLUBHOUSE5]: {
    id: FacilityId.CLUBHOUSE5,
    type: 'clubhouse',
    name: '第5クラブハウス',
    data: GEOJSON_FACILITIES.CLUBHOUSE5,
  },
  [FacilityId.HANGAR]: {
    id: FacilityId.HANGAR,
    type: 'clubhouse',
    name: '格納庫',
    data: GEOJSON_FACILITIES.HANGAR,
  },
  [FacilityId.FORMULA_PREFAB]: {
    id: FacilityId.FORMULA_PREFAB,
    type: 'clubhouse',
    name: 'プレハブ',
    data: GEOJSON_FACILITIES.FORMULA_PREFAB,
  },
  [FacilityId.TENNIS_HOUSE]: {
    id: FacilityId.TENNIS_HOUSE,
    type: 'clubhouse',
    name: '庭球場管理ハウス',
    data: GEOJSON_FACILITIES.TENNIS_HOUSE,
  },
  [FacilityId.KYUDO_HALL]: {
    id: FacilityId.KYUDO_HALL,
    type: 'clubhouse',
    name: '弓道場',
    data: GEOJSON_FACILITIES.KYUDO_HALL,
  },
  [FacilityId.GOLF]: {
    id: FacilityId.GOLF,
    type: 'clubhouse',
    name: 'ゴルフ練習場',
    data: GEOJSON_FACILITIES.GOLF,
  },
  [FacilityId.PLAYGROUND_MANAGEMENT]: {
    id: FacilityId.PLAYGROUND_MANAGEMENT,
    type: 'clubhouse',
    name: '総合運動場管理棟',
    data: GEOJSON_FACILITIES.PLAYGROUND_MANAGEMENT,
  },
  [FacilityId.DISASTER_CENTER]: {
    id: FacilityId.DISASTER_CENTER,
    type: 'other',
    name: '地域防災研究センター',
    data: GEOJSON_FACILITIES.DISASTER_CENTER,
  },
  [FacilityId.SEIREX_CENTER]: {
    id: FacilityId.SEIREX_CENTER,
    type: 'other',
    name: '耐震実験センター',
    data: GEOJSON_FACILITIES.SEIREX_CENTER,
  },
  [FacilityId.VIBRATION]: {
    id: FacilityId.VIBRATION,
    type: 'other',
    name: '振動実験棟',
    data: GEOJSON_FACILITIES.VIBRATION,
  },
  [FacilityId.CEA]: {
    id: FacilityId.CEA,
    type: 'other',
    name: '土木・建築実験棟',
    candidate: ['2号館実験棟'],
    data: GEOJSON_FACILITIES.CIVIL_ENGINEERING_ARCHITECTURE,
  },
  [FacilityId.HEADQUARTERS]: {
    id: FacilityId.HEADQUARTERS,
    type: 'other',
    name: '本部棟',
    data: GEOJSON_FACILITIES.HEADQUARTERS,
  },
  [FacilityId.HEADQUARTERS1]: {
    id: FacilityId.HEADQUARTERS1,
    type: 'other',
    name: '第1本部棟',
    data: GEOJSON_FACILITIES.HEADQUARTERS1,
  },
  [FacilityId.HEADQUARTERS2]: {
    id: FacilityId.HEADQUARTERS2,
    type: 'other',
    name: '第2本部棟',
    data: GEOJSON_FACILITIES.HEADQUARTERS2,
  },
  [FacilityId.RESEARCH]: {
    id: FacilityId.RESEARCH,
    type: 'other',
    name: '総合技術研究所',
    data: GEOJSON_FACILITIES.RESEARCH,
  },
  [FacilityId.ECO_POWER]: {
    id: FacilityId.ECO_POWER,
    type: 'other',
    name: 'エコ電力研究センター',
    data: GEOJSON_FACILITIES.ECO_POWER,
  },
  [FacilityId.COMPUTER]: {
    id: FacilityId.COMPUTER,
    type: 'other',
    name: '計算センター',
    data: GEOJSON_FACILITIES.COMPUTER,
  },
  [FacilityId.INFORMATION]: {
    id: FacilityId.INFORMATION,
    type: 'other',
    name: '情報教育センター',
    data: GEOJSON_FACILITIES.INFORMATION,
  },
  [FacilityId.LIBRARY]: {
    id: FacilityId.LIBRARY,
    type: 'other',
    name: '図書館',
    data: GEOJSON_FACILITIES.LIBRARY,
  },
  [FacilityId.CENTRAL_GARDEN]: {
    id: FacilityId.CENTRAL_GARDEN,
    type: 'ground',
    name: 'セントラルガーデン',
    data: GEOJSON_FACILITIES.CENTRAL_GARDEN,
  },
  [FacilityId.CENTRAL_SQUARE]: {
    id: FacilityId.CENTRAL_SQUARE,
    type: 'ground',
    name: 'セントラル広場',
    data: GEOJSON_FACILITIES.CENTRAL_SQUARE,
  },
  [FacilityId.TENNIS_COURT]: {
    id: FacilityId.TENNIS_COURT,
    type: 'ground',
    name: 'テニスコート',
    data: GEOJSON_FACILITIES.TENNIS_COURT,
  },
  [FacilityId.SOCCER_FIELD]: {
    id: FacilityId.SOCCER_FIELD,
    type: 'ground',
    name: 'サッカー場',
    data: GEOJSON_FACILITIES.SOCCER_FIELD,
  },
  [FacilityId.BALL_GAME_FIELD]: {
    id: FacilityId.BALL_GAME_FIELD,
    type: 'ground',
    name: '球技場',
    data: GEOJSON_FACILITIES.BALL_GAME_FIELD,
  },
  [FacilityId.BASEBALL_FIELD]: {
    id: FacilityId.BASEBALL_FIELD,
    type: 'ground',
    name: '野球場',
    data: GEOJSON_FACILITIES.BASEBALL_FIELD,
  },
  [FacilityId.ATHLETICS_FIELD]: {
    id: FacilityId.ATHLETICS_FIELD,
    type: 'ground',
    name: '陸上競技場',
    data: GEOJSON_FACILITIES.ATHLETICS_FIELD,
  },
  [FacilityId.ARCHERY_FIELD]: {
    id: FacilityId.ARCHERY_FIELD,
    type: 'ground',
    name: 'アーチェリー場',
    data: GEOJSON_FACILITIES.ARCHERY_FIELD,
  },
  [FacilityId.GYM]: {
    id: FacilityId.GYM,
    type: 'gym',
    name: '鉀徳館',
    candidate: ['体育館'],
    data: GEOJSON_FACILITIES.GYM,
  },
  [FacilityId.GYM_MIN]: {
    id: FacilityId.GYM_MIN,
    type: 'gym',
    name: '小体育館',
    data: GEOJSON_FACILITIES.GYM_MIN,
  },
  [FacilityId.PARKING1]: {
    id: FacilityId.PARKING1,
    type: 'parking',
    name: '第1学生駐車場',
    data: GEOJSON_FACILITIES.PARKING1,
  },
  [FacilityId.PARKING2]: {
    id: FacilityId.PARKING2,
    type: 'parking',
    name: '第2学生駐車場',
    data: GEOJSON_FACILITIES.PARKING2,
  },
  [FacilityId.PARKING3]: {
    id: FacilityId.PARKING3,
    type: 'parking',
    name: '第3学生駐車場',
    data: GEOJSON_FACILITIES.PARKING3,
  },
  [FacilityId.PARKING_BIKE]: {
    id: FacilityId.PARKING_BIKE,
    type: 'parking',
    name: 'バイク駐車場',
    data: GEOJSON_FACILITIES.PARKING_BIKE,
  },
  [FacilityId.BUS_STOP]: {
    id: FacilityId.BUS_STOP,
    type: 'parking',
    name: 'バス停',
    data: GEOJSON_FACILITIES.BUS_STOP,
  },
  [FacilityId.BUS_STOP_GETOFF_ONLY]: {
    id: FacilityId.BUS_STOP_GETOFF_ONLY,
    type: 'parking',
    name: 'バス停(降車専用)',
    data: GEOJSON_FACILITIES.BUS_STOP_GETOFF_ONLY,
  },
  [FacilityId.MAIN_GATE]: {
    id: FacilityId.MAIN_GATE,
    type: 'other',
    name: '正門',
    data: GEOJSON_FACILITIES.MAIN_GATE,
  },
  [FacilityId.SECURITY_ROOM]: {
    id: FacilityId.SECURITY_ROOM,
    type: 'other',
    name: '警備室',
    candidate: ['守衛室'],
    data: GEOJSON_FACILITIES.SECURITY_ROOM,
  },
  [FacilityId.TRAINING_DORMITORY]: {
    id: FacilityId.TRAINING_DORMITORY,
    type: 'other',
    name: '合宿寮',
    data: GEOJSON_FACILITIES.TRAINING_DORMITORY,
  },
  [FacilityId.STUDENT_DORMITORY]: {
    id: FacilityId.STUDENT_DORMITORY,
    type: 'other',
    name: '学生寮',
    data: GEOJSON_FACILITIES.STUDENT_DORMITORY,
  },
  [FacilityId.INTERNATIONAL_EXCHANGE_HALL]: {
    id: FacilityId.INTERNATIONAL_EXCHANGE_HALL,
    type: 'other',
    name: '国際交流会館',
    data: GEOJSON_FACILITIES.INTERNATIONAL_EXCHANGE_HALL,
  },
  [FacilityId.DORMITORY_CAFETERIA]: {
    id: FacilityId.DORMITORY_CAFETERIA,
    type: 'cafeteria',
    name: '寮食堂',
    data: GEOJSON_FACILITIES.DORMITORY_CAFETERIA,
  },
};

export const GEO_JSON_FACILITIES = values(FACILITIES_MAP);
