import { ID } from '@/utils/id';

export interface RoomMap {
  id: number;
  room: string;
  facilityId: string;
  floor?: `${number}` | `B${number}`;
}

const id = new ID();

export const ROOMS: RoomMap[] = [
  { id: id.get(), room: '10号6・7F', facilityId: '15' },
  { id: id.get(), room: 'G2110', facilityId: '15', floor: '1' },
  { id: id.get(), room: 'G2208', facilityId: '15', floor: '2' },
  { id: id.get(), room: 'G2209', facilityId: '15', floor: '2' },
  { id: id.get(), room: 'G2210', facilityId: '15', floor: '2' },
  { id: id.get(), room: 'G2309', facilityId: '15', floor: '3' },
  { id: id.get(), room: 'G2310', facilityId: '15', floor: '3' },
  { id: id.get(), room: 'G2311', facilityId: '15', floor: '3' },
  { id: id.get(), room: 'G2407', facilityId: '15', floor: '4' },
  { id: id.get(), room: 'G2408', facilityId: '15', floor: '4' },
  { id: id.get(), room: 'G2409', facilityId: '15', floor: '4' },
  { id: id.get(), room: 'G2504', facilityId: '15', floor: '5' },
  { id: id.get(), room: 'G2505', facilityId: '15', floor: '5' },
  { id: id.get(), room: 'G2506', facilityId: '15', floor: '5' },
  { id: id.get(), room: 'G2507', facilityId: '15', floor: '5' },
  { id: id.get(), room: 'G2604', facilityId: '15', floor: '6' },
  { id: id.get(), room: 'G2605', facilityId: '15', floor: '6' },
  { id: id.get(), room: 'G2606', facilityId: '15', floor: '6' },
  { id: id.get(), room: 'G2702', facilityId: '15', floor: '7' },
  { id: id.get(), room: 'G2707', facilityId: '15', floor: '7' },
  { id: id.get(), room: 'G2709', facilityId: '15', floor: '7' },
  { id: id.get(), room: 'G2710', facilityId: '15', floor: '7' },
  { id: id.get(), room: '1-101', facilityId: '1', floor: '1' },
  { id: id.get(), room: '1-102', facilityId: '1', floor: '1' },
  { id: id.get(), room: '1-103', facilityId: '1', floor: '1' },
  { id: id.get(), room: '1-104', facilityId: '1', floor: '1' },
  { id: id.get(), room: '1-105', facilityId: '1', floor: '1' },
  { id: id.get(), room: '1-106', facilityId: '1', floor: '1' },
  { id: id.get(), room: '1-108', facilityId: '1', floor: '1' },
  { id: id.get(), room: '1-202', facilityId: '1', floor: '2' },
  { id: id.get(), room: '1-203', facilityId: '1', floor: '2' },
  { id: id.get(), room: '1-204', facilityId: '1', floor: '2' },
  { id: id.get(), room: '1-205', facilityId: '1', floor: '2' },
  { id: id.get(), room: '1-206', facilityId: '1', floor: '2' },
  { id: id.get(), room: '1-207', facilityId: '1', floor: '2' },
  { id: id.get(), room: '1-208', facilityId: '1', floor: '2' },
  { id: id.get(), room: '1-210', facilityId: '1', floor: '2' },
  { id: id.get(), room: '1-211', facilityId: '1', floor: '2' },
  { id: id.get(), room: '1-212', facilityId: '1', floor: '2' },
  { id: id.get(), room: '1-213', facilityId: '1', floor: '2' },
  { id: id.get(), room: '1-214', facilityId: '1', floor: '2' },
  { id: id.get(), room: '1-301', facilityId: '1', floor: '3' },
  { id: id.get(), room: '1-303', facilityId: '1', floor: '3' },
  { id: id.get(), room: '1-401', facilityId: '1', floor: '4' },
  { id: id.get(), room: '1-501', facilityId: '1', floor: '5' },
  { id: id.get(), room: '1-502', facilityId: '1', floor: '5' },
  { id: id.get(), room: '1-601', facilityId: '1', floor: '6' },
  { id: id.get(), room: '1-602', facilityId: '1', floor: '6' },
  { id: id.get(), room: '1-701', facilityId: '1', floor: '7' },
  { id: id.get(), room: '1-702', facilityId: '1', floor: '7' },
  { id: id.get(), room: 'G3102', facilityId: '14', floor: '1' },
  { id: id.get(), room: 'G3201', facilityId: '14', floor: '2' },
  { id: id.get(), room: 'G3202', facilityId: '14', floor: '2' },
  { id: id.get(), room: 'G3203', facilityId: '14', floor: '2' },
  { id: id.get(), room: 'G3301', facilityId: '14', floor: '3' },
  { id: id.get(), room: 'G3302', facilityId: '14', floor: '3' },
  { id: id.get(), room: 'G3303', facilityId: '14', floor: '3' },
  { id: id.get(), room: 'G3401', facilityId: '14', floor: '4' },
  { id: id.get(), room: 'G3402', facilityId: '14', floor: '4' },
  { id: id.get(), room: 'G3403', facilityId: '14', floor: '4' },
  { id: id.get(), room: 'G3501', facilityId: '14', floor: '5' },
  { id: id.get(), room: 'G3502', facilityId: '14', floor: '5' },
  { id: id.get(), room: 'G3503', facilityId: '14', floor: '5' },
  { id: id.get(), room: 'G3504', facilityId: '14', floor: '5' },

  { id: id.get(), room: '2-601', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-602', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-603', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-604', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-605', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-606', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-607', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-608', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-609', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-610', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-611', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-612', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-613', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-614', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-615', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-616', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-617', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-618', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-619', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-620', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-501', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-502', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-503', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-504', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-505', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-506', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-507', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-508', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-509', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-510', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-511', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-512', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-513', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-514', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-515', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-516', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-517', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-518', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-519', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-401', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-402', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-403', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-404', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-405', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-406', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-407', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-408', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-409', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-410', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-411', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-412', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-413', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-414', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-415', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-416', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-417', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-418', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-419', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-301', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-302', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-303', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-304', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-305', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-306', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-307', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-308', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-309', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-310', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-311', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-312', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-313', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-314', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-315', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-316', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-317', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-318', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-319', facilityId: '4', floor: '3' },
  { id: id.get(), room: '2-201', facilityId: '4', floor: '2' },
  { id: id.get(), room: '2-202', facilityId: '4', floor: '2' },
  { id: id.get(), room: '2-203', facilityId: '4', floor: '2' },
  { id: id.get(), room: '2-204', facilityId: '4', floor: '2' },
  { id: id.get(), room: '2-205', facilityId: '4', floor: '2' },
  { id: id.get(), room: '2-206', facilityId: '4', floor: '2' },
  { id: id.get(), room: '2-207', facilityId: '4', floor: '2' },
  { id: id.get(), room: '2-208', facilityId: '4', floor: '2' },
  { id: id.get(), room: '2-209', facilityId: '4', floor: '2' },
  { id: id.get(), room: '2-210', facilityId: '4', floor: '2' },
  { id: id.get(), room: '2-211', facilityId: '4', floor: '2' },
  { id: id.get(), room: '2-212', facilityId: '4', floor: '2' },
  { id: id.get(), room: '2-213', facilityId: '4', floor: '2' },
  { id: id.get(), room: '2-214', facilityId: '4', floor: '2' },
  { id: id.get(), room: '2-215', facilityId: '4', floor: '2' },
  { id: id.get(), room: '2-216', facilityId: '4', floor: '2' },
  { id: id.get(), room: '2-217', facilityId: '4', floor: '2' },
  { id: id.get(), room: '2-101', facilityId: '4', floor: '1' },
  { id: id.get(), room: '2-102', facilityId: '4', floor: '1' },
  { id: id.get(), room: '2-103', facilityId: '4', floor: '1' },
  { id: id.get(), room: '2-104', facilityId: '4', floor: '1' },
  { id: id.get(), room: '2-105', facilityId: '4', floor: '1' },
  { id: id.get(), room: '2-106', facilityId: '4', floor: '1' },
  { id: id.get(), room: '2-107', facilityId: '4', floor: '1' },
  { id: id.get(), room: '2-108', facilityId: '4', floor: '1' },
  { id: id.get(), room: '2-109', facilityId: '4', floor: '1' },
  { id: id.get(), room: '2-B101', facilityId: '4', floor: 'B1' },
  { id: id.get(), room: '2-B102', facilityId: '4', floor: 'B1' },
  { id: id.get(), room: '2-B103', facilityId: '4', floor: 'B1' },
  { id: id.get(), room: '2-B104', facilityId: '4', floor: 'B1' },
  { id: id.get(), room: '2-B105', facilityId: '4', floor: 'B1' },
  { id: id.get(), room: '2-B106', facilityId: '4', floor: 'B1' },
  { id: id.get(), room: '2-B107', facilityId: '4', floor: 'B1' },
  { id: id.get(), room: '2-B108', facilityId: '4', floor: 'B1' },
  { id: id.get(), room: '2-B109', facilityId: '4', floor: 'B1' },
  { id: id.get(), room: '2-B201', facilityId: '4', floor: 'B2' },
  { id: id.get(), room: '2-B202', facilityId: '4', floor: 'B2' },
  { id: id.get(), room: '2-B203', facilityId: '4', floor: 'B2' },
  { id: id.get(), room: '2-B204', facilityId: '4', floor: 'B2' },
  { id: id.get(), room: '2-B205', facilityId: '4', floor: 'B2' },
  { id: id.get(), room: '2-B206', facilityId: '4', floor: 'B2' },
  { id: id.get(), room: '2-B207', facilityId: '4', floor: 'B2' },
  { id: id.get(), room: '2-B208', facilityId: '4', floor: 'B2' },
  { id: id.get(), room: '2-B209', facilityId: '4', floor: 'B2' },
  { id: id.get(), room: '2-B210', facilityId: '4', floor: 'B2' },
  { id: id.get(), room: '2-B211', facilityId: '4', floor: 'B2' },
  { id: id.get(), room: '2-B212', facilityId: '4', floor: 'B2' },
  { id: id.get(), room: '2-B213', facilityId: '4', floor: 'B2' },
  { id: id.get(), room: '2-B214', facilityId: '4', floor: 'B2' },

  { id: id.get(), room: '11-101', facilityId: '17' },
  { id: id.get(), room: '11-201', facilityId: '17' },
  { id: id.get(), room: '11-301', facilityId: '17' },
  { id: id.get(), room: '11-401', facilityId: '17' },
  { id: id.get(), room: '11-501', facilityId: '17' },
  { id: id.get(), room: '11-502', facilityId: '17' },
  { id: id.get(), room: '11-503', facilityId: '17' },
  { id: id.get(), room: '11-504', facilityId: '17' },
  { id: id.get(), room: '11-505', facilityId: '17' },
  { id: id.get(), room: '11-506', facilityId: '17' },
  { id: id.get(), room: '11-507', facilityId: '17' },
  { id: id.get(), room: '11-508', facilityId: '17' },
  { id: id.get(), room: '11-509', facilityId: '17' },
  { id: id.get(), room: '11-510', facilityId: '17' },

  { id: id.get(), room: 'E-多目的室', facilityId: '10' },
  { id: id.get(), room: 'ER実験室', facilityId: '10' },
  { id: id.get(), room: 'ER実験室1', facilityId: '10' },
  { id: id.get(), room: 'ER実験室2', facilityId: '10' },
  { id: id.get(), room: 'ER実験室3', facilityId: '10' },
  { id: id.get(), room: 'ER実験室4', facilityId: '10' },
  { id: id.get(), room: 'ER実験室5', facilityId: '10' },
  { id: id.get(), room: 'ER実験室6', facilityId: '10' },
  { id: id.get(), room: '機器実験室', facilityId: '10' },
  { id: id.get(), room: 'ER221', facilityId: '10' },
  { id: id.get(), room: 'ER222', facilityId: '10' },
  { id: id.get(), room: '計測実験室', facilityId: '10' },
  { id: id.get(), room: 'ER321', facilityId: '10' },
  { id: id.get(), room: 'ER322', facilityId: '10' },
  { id: id.get(), room: 'ER323', facilityId: '10' },
  { id: id.get(), room: 'ER324', facilityId: '10' },
  { id: id.get(), room: 'ER325', facilityId: '10' },

  { id: id.get(), room: 'M棟', facilityId: '11' },
  { id: id.get(), room: 'M102', facilityId: '11' },
  { id: id.get(), room: 'M111', facilityId: '11' },
  { id: id.get(), room: 'M405', facilityId: '11' },
  { id: id.get(), room: 'M502', facilityId: '11' },
  { id: id.get(), room: 'M508', facilityId: '11' },
  { id: id.get(), room: '7DAB棟', facilityId: '12' },
  { id: id.get(), room: '7材料実験室', facilityId: '12' },
  { id: id.get(), room: '7-201', facilityId: '12' },
  { id: id.get(), room: '7-202', facilityId: '12' },
  { id: id.get(), room: '7-203', facilityId: '12' },
  { id: id.get(), room: '7-204', facilityId: '12' },
  { id: id.get(), room: '7-205', facilityId: '12' },
  { id: id.get(), room: '7-206', facilityId: '12' },
  { id: id.get(), room: '7-207', facilityId: '12' },
  { id: id.get(), room: '7A製図室', facilityId: '12' },
  { id: id.get(), room: '7造形室', facilityId: '12' },
  { id: id.get(), room: '7B製図室', facilityId: '12' },
  { id: id.get(), room: '7-307', facilityId: '12' },
  { id: id.get(), room: '8-102', facilityId: '13' },
  { id: id.get(), room: '8-104', facilityId: '13' },
  { id: id.get(), room: '8-201', facilityId: '13' },
  { id: id.get(), room: '8-203', facilityId: '13' },
  { id: id.get(), room: '8-205', facilityId: '13' },
  { id: id.get(), room: '8-301', facilityId: '13' },
  { id: id.get(), room: '8-303', facilityId: '13' },
  { id: id.get(), room: '8-304', facilityId: '13' },
  { id: id.get(), room: '12-ゼミ室', facilityId: '18' },
  { id: id.get(), room: '12号講義室', facilityId: '18' },
  { id: id.get(), room: 'みらい工房', facilityId: '18' },
  { id: id.get(), room: '12-201', facilityId: '18', floor: '2' },
  { id: id.get(), room: '12-202', facilityId: '18', floor: '2' },
  { id: id.get(), room: '12-303', facilityId: '18', floor: '3' },
  { id: id.get(), room: '13-101', facilityId: '19', floor: '1' },
  { id: id.get(), room: '13-201', facilityId: '19', floor: '2' },
  { id: id.get(), room: '13-301', facilityId: '19', floor: '3' },
  { id: id.get(), room: '13-302', facilityId: '19', floor: '3' },
  { id: id.get(), room: '13-303', facilityId: '19', floor: '3' },
  { id: id.get(), room: '13-401', facilityId: '19', floor: '4' },
  { id: id.get(), room: '13-402', facilityId: '19', floor: '4' },
  { id: id.get(), room: '13-403', facilityId: '19', floor: '4' },
  { id: id.get(), room: '14-201', facilityId: '20', floor: '2' },
  { id: id.get(), room: '14-202', facilityId: '20', floor: '2' },
  { id: id.get(), room: '14-301', facilityId: '20', floor: '3' },
  { id: id.get(), room: '14-302', facilityId: '20', floor: '3' },
  { id: id.get(), room: 'セ-実習室1,2', facilityId: '22' },
  { id: id.get(), room: 'セ-講義室', facilityId: '22' },
  { id: id.get(), room: 'PC学習室', facilityId: '22' },
  { id: id.get(), room: 'セ-実習室1', facilityId: '22' },
  { id: id.get(), room: '端末室', facilityId: '22' },
  { id: id.get(), room: 'マイコン室1', facilityId: '22' },
  { id: id.get(), room: 'マイコン室2', facilityId: '22' },
  { id: id.get(), room: 'マイコン室1,2', facilityId: '22' },
  { id: id.get(), room: 'セ-実習室2', facilityId: '22' },
  { id: id.get(), room: '情教実習室A,B', facilityId: '23' },
  { id: id.get(), room: 'NWルーム', facilityId: '23' },
  { id: id.get(), room: '情教実習室A', facilityId: '23' },
  { id: id.get(), room: '情教実習室B', facilityId: '23' },
  { id: id.get(), room: '愛和講堂', facilityId: '32' },
  { id: id.get(), room: '総-視聴覚室', facilityId: '24' },
  { id: id.get(), room: '14-101 マルチファンクションルーム', facilityId: '20', floor: '1' },
  { id: id.get(), room: '14-102 マルチファンクションルーム', facilityId: '20', floor: '1' },
  { id: id.get(), room: '14-104 プロジェクトルーム', facilityId: '20', floor: '1' },
  { id: id.get(), room: '14-105 プロジェクトルーム', facilityId: '20', floor: '1' },
  { id: id.get(), room: '14-106 プロジェクトルーム', facilityId: '20', floor: '1' },
  { id: id.get(), room: '14-107 プロジェクトルーム', facilityId: '20', floor: '1' },
  { id: id.get(), room: '14-108 プロジェクトルーム', facilityId: '20', floor: '1' },
  { id: id.get(), room: '14-109 ミーティングルーム', facilityId: '20', floor: '1' },
  { id: id.get(), room: '14-201 講義室', facilityId: '20', floor: '2' },
  { id: id.get(), room: '14-202 講義室', facilityId: '20', floor: '2' },
  { id: id.get(), room: '14-204 ミーティングルーム', facilityId: '20', floor: '2' },
  { id: id.get(), room: '14-205 ミーティングルーム', facilityId: '20', floor: '2' },
  { id: id.get(), room: '14-206 大学院講義室', facilityId: '20', floor: '2' },
  { id: id.get(), room: '14-207 大学院講義室', facilityId: '20', floor: '2' },
  { id: id.get(), room: '14-301 講義室', facilityId: '20', floor: '3' },
  { id: id.get(), room: '14-302 講義室', facilityId: '20', floor: '3' },
  { id: id.get(), room: '14-304 学部長室', facilityId: '20', floor: '3' },
  { id: id.get(), room: '14-305 研究科長室', facilityId: '20', floor: '3' },
  { id: id.get(), room: '14-306 事務室', facilityId: '20', floor: '3' },
  { id: id.get(), room: '14-307 印刷室', facilityId: '20', floor: '3' },
  { id: id.get(), room: '14-308 非常勤控室', facilityId: '20', floor: '3' },
  { id: id.get(), room: '14-309 会議室', facilityId: '20', floor: '3' },
  { id: id.get(), room: '14-310 会議室', facilityId: '20', floor: '3' },
  { id: id.get(), room: '玉森 聡研究室', facilityId: '20', floor: '4' },
  { id: id.get(), room: '森本 正志研究室', facilityId: '20', floor: '4' },
  { id: id.get(), room: '河辺 義信研究室', facilityId: '20', floor: '4' },
  { id: id.get(), room: '水野 勝教研究室', facilityId: '20', floor: '4' },
  { id: id.get(), room: '内藤 克浩研究室', facilityId: '20', floor: '4' },
  { id: id.get(), room: '小野木 克明研究室', facilityId: '20', floor: '5' },
  { id: id.get(), room: '伊藤 暢浩研究室', facilityId: '20', floor: '5' },
  { id: id.get(), room: '内種 岳詞研究室', facilityId: '20', floor: '5' },
  { id: id.get(), room: '山本 貴史研究室', facilityId: '20', floor: '5' },
  { id: id.get(), room: '鈴木 晋研究室', facilityId: '20', floor: '5' },
  { id: id.get(), room: '梶 克彦研究室', facilityId: '20', floor: '5' },
  { id: id.get(), room: '14-601', facilityId: '20', floor: '6' },
  { id: id.get(), room: '澤野 弘明 研究室', facilityId: '20', floor: '6' },
  { id: id.get(), room: '菱田 隆彰研究室', facilityId: '20', floor: '6' },
  { id: id.get(), room: '14-609', facilityId: '20', floor: '6' },
  { id: id.get(), room: '塚田 敏彦研究室', facilityId: '20', floor: '6' },
  { id: id.get(), room: '中村 栄治研究室', facilityId: '20', floor: '6' },
  { id: id.get(), room: '伊藤 雅研究室', facilityId: '20', floor: '7' },
  { id: id.get(), room: '徳久 良子研究室', facilityId: '20', floor: '7' },
  { id: id.get(), room: '小栗 真弥研究室', facilityId: '20', floor: '7' },
  { id: id.get(), room: '松河 剛司研究室', facilityId: '20', floor: '7' },
  { id: id.get(), room: '水野 慎士研究室', facilityId: '20', floor: '7' },
] as const;

export type RoomIds = (typeof ROOMS)[number]['id'];
