import { ID } from '@/utils/id';

export interface RoomMap {
  id: number;
  room: string;
  buidlingId: number;
  floor?: `${number}` | `B${number}`;
}

const id = new ID();

export const ROOM_MAP: RoomMap[] = [
  { id: id.get(), room: '10号6・7F', buidlingId: 15 },
  { id: id.get(), room: 'G2110', buidlingId: 15, floor: '1' },
  { id: id.get(), room: 'G2208', buidlingId: 15, floor: '2' },
  { id: id.get(), room: 'G2209', buidlingId: 15, floor: '2' },
  { id: id.get(), room: 'G2210', buidlingId: 15, floor: '2' },
  { id: id.get(), room: 'G2309', buidlingId: 15, floor: '3' },
  { id: id.get(), room: 'G2310', buidlingId: 15, floor: '3' },
  { id: id.get(), room: 'G2311', buidlingId: 15, floor: '3' },
  { id: id.get(), room: 'G2407', buidlingId: 15, floor: '4' },
  { id: id.get(), room: 'G2408', buidlingId: 15, floor: '4' },
  { id: id.get(), room: 'G2409', buidlingId: 15, floor: '4' },
  { id: id.get(), room: 'G2504', buidlingId: 15, floor: '5' },
  { id: id.get(), room: 'G2505', buidlingId: 15, floor: '5' },
  { id: id.get(), room: 'G2506', buidlingId: 15, floor: '5' },
  { id: id.get(), room: 'G2507', buidlingId: 15, floor: '5' },
  { id: id.get(), room: 'G2604', buidlingId: 15, floor: '6' },
  { id: id.get(), room: 'G2605', buidlingId: 15, floor: '6' },
  { id: id.get(), room: 'G2606', buidlingId: 15, floor: '6' },
  { id: id.get(), room: 'G2702', buidlingId: 15, floor: '7' },
  { id: id.get(), room: 'G2707', buidlingId: 15, floor: '7' },
  { id: id.get(), room: 'G2709', buidlingId: 15, floor: '7' },
  { id: id.get(), room: 'G2710', buidlingId: 15, floor: '7' },
  { id: id.get(), room: '1-101', buidlingId: 1, floor: '1' },
  { id: id.get(), room: '1-102', buidlingId: 1, floor: '1' },
  { id: id.get(), room: '1-103', buidlingId: 1, floor: '1' },
  { id: id.get(), room: '1-104', buidlingId: 1, floor: '1' },
  { id: id.get(), room: '1-105', buidlingId: 1, floor: '1' },
  { id: id.get(), room: '1-106', buidlingId: 1, floor: '1' },
  { id: id.get(), room: '1-108', buidlingId: 1, floor: '1' },
  { id: id.get(), room: '1-202', buidlingId: 1, floor: '2' },
  { id: id.get(), room: '1-203', buidlingId: 1, floor: '2' },
  { id: id.get(), room: '1-204', buidlingId: 1, floor: '2' },
  { id: id.get(), room: '1-205', buidlingId: 1, floor: '2' },
  { id: id.get(), room: '1-206', buidlingId: 1, floor: '2' },
  { id: id.get(), room: '1-207', buidlingId: 1, floor: '2' },
  { id: id.get(), room: '1-208', buidlingId: 1, floor: '2' },
  { id: id.get(), room: '1-210', buidlingId: 1, floor: '2' },
  { id: id.get(), room: '1-211', buidlingId: 1, floor: '2' },
  { id: id.get(), room: '1-212', buidlingId: 1, floor: '2' },
  { id: id.get(), room: '1-213', buidlingId: 1, floor: '2' },
  { id: id.get(), room: '1-214', buidlingId: 1, floor: '2' },
  { id: id.get(), room: '1-301', buidlingId: 1, floor: '3' },
  { id: id.get(), room: '1-303', buidlingId: 1, floor: '3' },
  { id: id.get(), room: '1-401', buidlingId: 1, floor: '4' },
  { id: id.get(), room: '1-501', buidlingId: 1, floor: '5' },
  { id: id.get(), room: '1-502', buidlingId: 1, floor: '5' },
  { id: id.get(), room: '1-601', buidlingId: 1, floor: '6' },
  { id: id.get(), room: '1-602', buidlingId: 1, floor: '6' },
  { id: id.get(), room: '1-701', buidlingId: 1, floor: '7' },
  { id: id.get(), room: '1-702', buidlingId: 1, floor: '7' },
  { id: id.get(), room: 'G3102', buidlingId: 14, floor: '1' },
  { id: id.get(), room: 'G3201', buidlingId: 14, floor: '2' },
  { id: id.get(), room: 'G3202', buidlingId: 14, floor: '2' },
  { id: id.get(), room: 'G3203', buidlingId: 14, floor: '2' },
  { id: id.get(), room: 'G3301', buidlingId: 14, floor: '3' },
  { id: id.get(), room: 'G3302', buidlingId: 14, floor: '3' },
  { id: id.get(), room: 'G3303', buidlingId: 14, floor: '3' },
  { id: id.get(), room: 'G3401', buidlingId: 14, floor: '4' },
  { id: id.get(), room: 'G3402', buidlingId: 14, floor: '4' },
  { id: id.get(), room: 'G3403', buidlingId: 14, floor: '4' },
  { id: id.get(), room: 'G3501', buidlingId: 14, floor: '5' },
  { id: id.get(), room: 'G3502', buidlingId: 14, floor: '5' },
  { id: id.get(), room: 'G3503', buidlingId: 14, floor: '5' },
  { id: id.get(), room: 'G3504', buidlingId: 14, floor: '5' },

  { id: id.get(), room: '2-601', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-602', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-603', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-604', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-605', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-606', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-607', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-608', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-609', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-610', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-611', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-612', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-613', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-614', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-615', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-616', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-617', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-618', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-619', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-620', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-501', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-502', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-503', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-504', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-505', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-506', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-507', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-508', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-509', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-510', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-511', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-512', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-513', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-514', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-515', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-516', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-517', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-518', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-519', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-401', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-402', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-403', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-404', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-405', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-406', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-407', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-408', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-409', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-410', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-411', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-412', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-413', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-414', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-415', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-416', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-417', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-418', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-419', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-301', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-302', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-303', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-304', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-305', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-306', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-307', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-308', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-309', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-310', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-311', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-312', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-313', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-314', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-315', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-316', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-317', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-318', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-319', buidlingId: 4, floor: '3' },
  { id: id.get(), room: '2-201', buidlingId: 4, floor: '2' },
  { id: id.get(), room: '2-202', buidlingId: 4, floor: '2' },
  { id: id.get(), room: '2-203', buidlingId: 4, floor: '2' },
  { id: id.get(), room: '2-204', buidlingId: 4, floor: '2' },
  { id: id.get(), room: '2-205', buidlingId: 4, floor: '2' },
  { id: id.get(), room: '2-206', buidlingId: 4, floor: '2' },
  { id: id.get(), room: '2-207', buidlingId: 4, floor: '2' },
  { id: id.get(), room: '2-208', buidlingId: 4, floor: '2' },
  { id: id.get(), room: '2-209', buidlingId: 4, floor: '2' },
  { id: id.get(), room: '2-210', buidlingId: 4, floor: '2' },
  { id: id.get(), room: '2-211', buidlingId: 4, floor: '2' },
  { id: id.get(), room: '2-212', buidlingId: 4, floor: '2' },
  { id: id.get(), room: '2-213', buidlingId: 4, floor: '2' },
  { id: id.get(), room: '2-214', buidlingId: 4, floor: '2' },
  { id: id.get(), room: '2-215', buidlingId: 4, floor: '2' },
  { id: id.get(), room: '2-216', buidlingId: 4, floor: '2' },
  { id: id.get(), room: '2-217', buidlingId: 4, floor: '2' },
  { id: id.get(), room: '2-101', buidlingId: 4, floor: '1' },
  { id: id.get(), room: '2-102', buidlingId: 4, floor: '1' },
  { id: id.get(), room: '2-103', buidlingId: 4, floor: '1' },
  { id: id.get(), room: '2-104', buidlingId: 4, floor: '1' },
  { id: id.get(), room: '2-105', buidlingId: 4, floor: '1' },
  { id: id.get(), room: '2-106', buidlingId: 4, floor: '1' },
  { id: id.get(), room: '2-107', buidlingId: 4, floor: '1' },
  { id: id.get(), room: '2-108', buidlingId: 4, floor: '1' },
  { id: id.get(), room: '2-109', buidlingId: 4, floor: '1' },
  { id: id.get(), room: '2-B101', buidlingId: 4, floor: 'B1' },
  { id: id.get(), room: '2-B102', buidlingId: 4, floor: 'B1' },
  { id: id.get(), room: '2-B103', buidlingId: 4, floor: 'B1' },
  { id: id.get(), room: '2-B104', buidlingId: 4, floor: 'B1' },
  { id: id.get(), room: '2-B105', buidlingId: 4, floor: 'B1' },
  { id: id.get(), room: '2-B106', buidlingId: 4, floor: 'B1' },
  { id: id.get(), room: '2-B107', buidlingId: 4, floor: 'B1' },
  { id: id.get(), room: '2-B108', buidlingId: 4, floor: 'B1' },
  { id: id.get(), room: '2-B109', buidlingId: 4, floor: 'B1' },
  { id: id.get(), room: '2-B201', buidlingId: 4, floor: 'B2' },
  { id: id.get(), room: '2-B202', buidlingId: 4, floor: 'B2' },
  { id: id.get(), room: '2-B203', buidlingId: 4, floor: 'B2' },
  { id: id.get(), room: '2-B204', buidlingId: 4, floor: 'B2' },
  { id: id.get(), room: '2-B205', buidlingId: 4, floor: 'B2' },
  { id: id.get(), room: '2-B206', buidlingId: 4, floor: 'B2' },
  { id: id.get(), room: '2-B207', buidlingId: 4, floor: 'B2' },
  { id: id.get(), room: '2-B208', buidlingId: 4, floor: 'B2' },
  { id: id.get(), room: '2-B209', buidlingId: 4, floor: 'B2' },
  { id: id.get(), room: '2-B210', buidlingId: 4, floor: 'B2' },
  { id: id.get(), room: '2-B211', buidlingId: 4, floor: 'B2' },
  { id: id.get(), room: '2-B212', buidlingId: 4, floor: 'B2' },
  { id: id.get(), room: '2-B213', buidlingId: 4, floor: 'B2' },
  { id: id.get(), room: '2-B214', buidlingId: 4, floor: 'B2' },

  { id: id.get(), room: '11-101', buidlingId: 17 },
  { id: id.get(), room: '11-201', buidlingId: 17 },
  { id: id.get(), room: '11-301', buidlingId: 17 },
  { id: id.get(), room: '11-401', buidlingId: 17 },
  { id: id.get(), room: '11-501', buidlingId: 17 },
  { id: id.get(), room: '11-502', buidlingId: 17 },
  { id: id.get(), room: '11-503', buidlingId: 17 },
  { id: id.get(), room: '11-504', buidlingId: 17 },
  { id: id.get(), room: '11-505', buidlingId: 17 },
  { id: id.get(), room: '11-506', buidlingId: 17 },
  { id: id.get(), room: '11-507', buidlingId: 17 },
  { id: id.get(), room: '11-508', buidlingId: 17 },
  { id: id.get(), room: '11-509', buidlingId: 17 },
  { id: id.get(), room: '11-510', buidlingId: 17 },

  { id: id.get(), room: 'E-多目的室', buidlingId: 10 },
  { id: id.get(), room: 'ER実験室', buidlingId: 10 },
  { id: id.get(), room: 'ER実験室1', buidlingId: 10 },
  { id: id.get(), room: 'ER実験室2', buidlingId: 10 },
  { id: id.get(), room: 'ER実験室3', buidlingId: 10 },
  { id: id.get(), room: 'ER実験室4', buidlingId: 10 },
  { id: id.get(), room: 'ER実験室5', buidlingId: 10 },
  { id: id.get(), room: 'ER実験室6', buidlingId: 10 },
  { id: id.get(), room: '機器実験室', buidlingId: 10 },
  { id: id.get(), room: 'ER221', buidlingId: 10 },
  { id: id.get(), room: 'ER222', buidlingId: 10 },
  { id: id.get(), room: '計測実験室', buidlingId: 10 },
  { id: id.get(), room: 'ER321', buidlingId: 10 },
  { id: id.get(), room: 'ER322', buidlingId: 10 },
  { id: id.get(), room: 'ER323', buidlingId: 10 },
  { id: id.get(), room: 'ER324', buidlingId: 10 },
  { id: id.get(), room: 'ER325', buidlingId: 10 },

  { id: id.get(), room: 'M棟', buidlingId: 11 },
  { id: id.get(), room: 'M102', buidlingId: 11 },
  { id: id.get(), room: 'M111', buidlingId: 11 },
  { id: id.get(), room: 'M405', buidlingId: 11 },
  { id: id.get(), room: 'M502', buidlingId: 11 },
  { id: id.get(), room: 'M508', buidlingId: 11 },
  { id: id.get(), room: '7DAB棟', buidlingId: 12 },
  { id: id.get(), room: '7材料実験室', buidlingId: 12 },
  { id: id.get(), room: '7-201', buidlingId: 12 },
  { id: id.get(), room: '7-202', buidlingId: 12 },
  { id: id.get(), room: '7-203', buidlingId: 12 },
  { id: id.get(), room: '7-204', buidlingId: 12 },
  { id: id.get(), room: '7-205', buidlingId: 12 },
  { id: id.get(), room: '7-206', buidlingId: 12 },
  { id: id.get(), room: '7-207', buidlingId: 12 },
  { id: id.get(), room: '7A製図室', buidlingId: 12 },
  { id: id.get(), room: '7造形室', buidlingId: 12 },
  { id: id.get(), room: '7B製図室', buidlingId: 12 },
  { id: id.get(), room: '7-307', buidlingId: 12 },
  { id: id.get(), room: '8-102', buidlingId: 13 },
  { id: id.get(), room: '8-104', buidlingId: 13 },
  { id: id.get(), room: '8-201', buidlingId: 13 },
  { id: id.get(), room: '8-203', buidlingId: 13 },
  { id: id.get(), room: '8-205', buidlingId: 13 },
  { id: id.get(), room: '8-301', buidlingId: 13 },
  { id: id.get(), room: '8-303', buidlingId: 13 },
  { id: id.get(), room: '8-304', buidlingId: 13 },
  { id: id.get(), room: '12-ゼミ室', buidlingId: 18 },
  { id: id.get(), room: '12号講義室', buidlingId: 18 },
  { id: id.get(), room: 'みらい工房', buidlingId: 18 },
  { id: id.get(), room: '12-201', buidlingId: 18, floor: '2' },
  { id: id.get(), room: '12-202', buidlingId: 18, floor: '2' },
  { id: id.get(), room: '12-303', buidlingId: 18, floor: '3' },
  { id: id.get(), room: '13-101', buidlingId: 19, floor: '1' },
  { id: id.get(), room: '13-201', buidlingId: 19, floor: '2' },
  { id: id.get(), room: '13-301', buidlingId: 19, floor: '3' },
  { id: id.get(), room: '13-302', buidlingId: 19, floor: '3' },
  { id: id.get(), room: '13-303', buidlingId: 19, floor: '3' },
  { id: id.get(), room: '13-401', buidlingId: 19, floor: '4' },
  { id: id.get(), room: '13-402', buidlingId: 19, floor: '4' },
  { id: id.get(), room: '13-403', buidlingId: 19, floor: '4' },
  { id: id.get(), room: '14-201', buidlingId: 20, floor: '2' },
  { id: id.get(), room: '14-202', buidlingId: 20, floor: '2' },
  { id: id.get(), room: '14-301', buidlingId: 20, floor: '3' },
  { id: id.get(), room: '14-302', buidlingId: 20, floor: '3' },
  { id: id.get(), room: 'セ-実習室1,2', buidlingId: 22 },
  { id: id.get(), room: 'セ-講義室', buidlingId: 22 },
  { id: id.get(), room: 'PC学習室', buidlingId: 22 },
  { id: id.get(), room: 'セ-実習室1', buidlingId: 22 },
  { id: id.get(), room: '端末室', buidlingId: 22 },
  { id: id.get(), room: 'マイコン室1', buidlingId: 22 },
  { id: id.get(), room: 'マイコン室2', buidlingId: 22 },
  { id: id.get(), room: 'マイコン室1,2', buidlingId: 22 },
  { id: id.get(), room: 'セ-実習室2', buidlingId: 22 },
  { id: id.get(), room: '情教実習室A,B', buidlingId: 23 },
  { id: id.get(), room: 'NWルーム', buidlingId: 23 },
  { id: id.get(), room: '情教実習室A', buidlingId: 23 },
  { id: id.get(), room: '情教実習室B', buidlingId: 23 },
  { id: id.get(), room: '愛和講堂', buidlingId: 32 },
  { id: id.get(), room: '総-視聴覚室', buidlingId: 24 },
  { id: id.get(), room: '14-101 マルチファンクションルーム', buidlingId: 20, floor: '1' },
  { id: id.get(), room: '14-102 マルチファンクションルーム', buidlingId: 20, floor: '1' },
  { id: id.get(), room: '14-104 プロジェクトルーム', buidlingId: 20, floor: '1' },
  { id: id.get(), room: '14-105 プロジェクトルーム', buidlingId: 20, floor: '1' },
  { id: id.get(), room: '14-106 プロジェクトルーム', buidlingId: 20, floor: '1' },
  { id: id.get(), room: '14-107 プロジェクトルーム', buidlingId: 20, floor: '1' },
  { id: id.get(), room: '14-108 プロジェクトルーム', buidlingId: 20, floor: '1' },
  { id: id.get(), room: '14-109 ミーティングルーム', buidlingId: 20, floor: '1' },
  { id: id.get(), room: '14-201 講義室', buidlingId: 20, floor: '2' },
  { id: id.get(), room: '14-202 講義室', buidlingId: 20, floor: '2' },
  { id: id.get(), room: '14-204 ミーティングルーム', buidlingId: 20, floor: '2' },
  { id: id.get(), room: '14-205 ミーティングルーム', buidlingId: 20, floor: '2' },
  { id: id.get(), room: '14-206 大学院講義室', buidlingId: 20, floor: '2' },
  { id: id.get(), room: '14-207 大学院講義室', buidlingId: 20, floor: '2' },
  { id: id.get(), room: '14-301 講義室', buidlingId: 20, floor: '3' },
  { id: id.get(), room: '14-302 講義室', buidlingId: 20, floor: '3' },
  { id: id.get(), room: '14-304 学部長室', buidlingId: 20, floor: '3' },
  { id: id.get(), room: '14-305 研究科長室', buidlingId: 20, floor: '3' },
  { id: id.get(), room: '14-306 事務室', buidlingId: 20, floor: '3' },
  { id: id.get(), room: '14-307 印刷室', buidlingId: 20, floor: '3' },
  { id: id.get(), room: '14-308 非常勤控室', buidlingId: 20, floor: '3' },
  { id: id.get(), room: '14-309 会議室', buidlingId: 20, floor: '3' },
  { id: id.get(), room: '14-310 会議室', buidlingId: 20, floor: '3' },
  { id: id.get(), room: '玉森 聡研究室', buidlingId: 20, floor: '4' },
  { id: id.get(), room: '森本 正志研究室', buidlingId: 20, floor: '4' },
  { id: id.get(), room: '河辺 義信研究室', buidlingId: 20, floor: '4' },
  { id: id.get(), room: '水野 勝教研究室', buidlingId: 20, floor: '4' },
  { id: id.get(), room: '内藤 克浩研究室', buidlingId: 20, floor: '4' },
  { id: id.get(), room: '小野木 克明研究室', buidlingId: 20, floor: '5' },
  { id: id.get(), room: '伊藤 暢浩研究室', buidlingId: 20, floor: '5' },
  { id: id.get(), room: '内種 岳詞研究室', buidlingId: 20, floor: '5' },
  { id: id.get(), room: '山本 貴史研究室', buidlingId: 20, floor: '5' },
  { id: id.get(), room: '鈴木 晋研究室', buidlingId: 20, floor: '5' },
  { id: id.get(), room: '梶 克彦研究室', buidlingId: 20, floor: '5' },
  { id: id.get(), room: '14-601', buidlingId: 20, floor: '6' },
  { id: id.get(), room: '澤野 弘明 研究室', buidlingId: 20, floor: '6' },
  { id: id.get(), room: '菱田 隆彰研究室', buidlingId: 20, floor: '6' },
  { id: id.get(), room: '14-609', buidlingId: 20, floor: '6' },
  { id: id.get(), room: '塚田 敏彦研究室', buidlingId: 20, floor: '6' },
  { id: id.get(), room: '中村 栄治研究室', buidlingId: 20, floor: '6' },
  { id: id.get(), room: '伊藤 雅研究室', buidlingId: 20, floor: '7' },
  { id: id.get(), room: '徳久 良子研究室', buidlingId: 20, floor: '7' },
  { id: id.get(), room: '小栗 真弥研究室', buidlingId: 20, floor: '7' },
  { id: id.get(), room: '松河 剛司研究室', buidlingId: 20, floor: '7' },
  { id: id.get(), room: '水野 慎士研究室', buidlingId: 20, floor: '7' },
] as const;

export type RoomIds = (typeof ROOM_MAP)[number]['id'];
